name : 02-workflow Events

on : 
    push:
    pull_request:
    schedule:
      - cron: '*/5 * * * *'
    workflow_dispatch:
      



jobs:
  echo:
     runs-on: ubuntu-latest
     steps:
       - name: show the tigger
         run : echo "I've been triggerd by a(n) ${{github.event_name}}"
