name: 03-workflow Runners

on:
#   push:
  workflow_dispatch: 

jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Runner on Ubuntu
        run: echo "Runner OS -> $RUNNER_OS"
    
  
  windows-runner:
    runs-on: windows-latest
    steps:
      - name: Workflow Runner on Windows
        shell: bash
        run: echo "Runner OS -> $RUNNER_OS"
    
  
